### ISSUE TITLE
How to use repository for NMT

### ISSUE THREAD

**Issue by kr-sundaram** [patelrajnath/pytorch-dl#8]
Hey, thanks for making the repo public.

I am developing an NMT system for En to De, De to En, Fr to En and En to Fr and I would like to use this repository. I have few doubts hope you clarify them.

1. As per the README file, this repository can be used for BERT and BART pre-training. I researched that BART is a novel approach for training a robust NMT system. Understanding of my BART is, it is a transformer based Encoder-Decoder architecture in which we can train the NMT system using pre-trained model like BERT in both Encoder and Decoder neural network. I want to know how can we make use use of pre-training of BART model in NMT architecture (of this repo) in order to build a robust NMT system.

2. How to tackle Transliteration of named-entities incorporation with Translation?
What i currently thought of tackling this is by using 3 models in my final translation pipeline i.e. NER model, NMT and Transliteration model and description are as follows. (Please suggest me if i am wrong somewhere or if you have better solution to this.)
a. Let's consider, the named entities (NE) of person and organization name. So initially, after cleaning the dataset, i will have a trained model lets say spaCy, which will be used to identify the NE in the dataset and all the sentences of src and tgt language will be replaced with tags, lets say /PER for person and /ORG for organization. And then, by using sentencepiece, i will train the tokenizer with SOS, EOS, /PER and /ORG tags such that NE tags will be there in the Vocab. I would also train a separate model for for transliterating NEs. For example,

En - My name is Kumar and i work for XY.
De - My name ist Kumar und ich arbeit bei XY.

After replacing NE with NE tags. the training data will look like below.

En - My name is /PER and i work for /ORG.
De - My name ist /PER und ich arbeit bei /ORG.

And after replacing the NE with corresponding tags we will train the sentencepiece tokenizer and apply it on training data accordingly as you have done here in the repository.

So once, the NMT model is trained. While translating, firstly, the src sentence has to go through the NER model to identify the NE which will be replaced by tags like /PER or /ORG and the sentence gets translated and then NEs gets transliterated and then transliterated NEs will replace the tags at their respective positions in the translated sentence.

Please let me know if you have any comments.

3. Whether your repository can be used for making applications for business purposes. I assume GNU license gives that authority but still i want to be just sure as you have the copyrights.

4. How to use repository for performing back-translation as i have less amount of parallel data and more amount of monolingual data.

Please let me know in case of concerns,
Thanks for your patience!

**Comment by patelrajnath** [comment]
To use mBart for NMT, you need to train the mBart (I used mbert in the code which is incorrect, I'll fix that in next merge) model using the available monolingual corpus then you could use the same for fine-tuning on parallel corpus. 

The fine-tuning part is not yet implemented separately. But that should be straight forward inline with train_nmt.py. 

Probably you can skip the NER part as there are quite good methods using you can force copying NERs in NMT model itself. Look for copying mechanism in NMT. 

Yes, it is open source. Also, PRs are welcome for any updates/improvements.

**Comment by patelrajnath** [comment]
Hi, I added the feature to run mBART training and then use the same for NMT fine-tuning. Checkout the README instructions for sample usage. 

If that answers your issue close this.
